#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from release_common import iter_files, sha256_bytes, sha256_file

GATES = {
    "source_checks": "Shell/Python/XML/YAML checks and source invariants",
    "pure_kotlin_jvm": "Pure Kotlin/JVM topology tests",
    "apk_compile": "Android debug APK compile",
    "native_16k": "16 KiB PT_LOAD verifier for native APK ELF files",
    "qemu_dependency_closure": "Packaged QEMU DT_NEEDED/hash/alignment closure",
    "fake_rfb": "Loopback fake-RFB protocol integration test",
    "device_farm_smoke": "Optional real-device/device-farm smoke run",
    "p1_physical": "Fresh P1 physical-device acceptance proof",
    "p2_physical": "Fresh P2 framework-ready physical-device acceptance proof",
    "p3_display_physical": "Fresh P3 framebuffer physical-device acceptance proof",
    "p3_input_physical": "Deterministic host-input to guest-ack physical proof",
}


def load_lock(root: Path) -> dict:
    return json.loads((root / "config/toolchain.lock.json").read_text(encoding="utf-8"))


def inventory(root: Path) -> list[dict]:
    result = []
    for path in iter_files(root):
        rel = path.relative_to(root).as_posix()
        result.append({"path": rel, "bytes": path.stat().st_size, "sha256": sha256_file(path)})
    return result


def render_filelist(entries: list[dict]) -> bytes:
    lines = [
        "# Virtual Android deterministic file inventory",
        "# Generated by scripts/generate_release_metadata.py",
        "# Generated metadata files FILELIST.txt and release/release-manifest.json are excluded to avoid recursive hashes.",
        "# sha256  path",
    ]
    lines.extend(f"{entry['sha256']}  {entry['path']}" for entry in entries)
    return ("\n".join(lines) + "\n").encode("utf-8")


def qemu_runtime_info(root: Path) -> dict:
    manifest = root / "app/src/main/assets/qemu/qemu-runtime-manifest.json"
    if not manifest.is_file():
        return {"state": "NOT_VERIFIED", "reason": "No imported QEMU runtime manifest is present in this source snapshot"}
    data = json.loads(manifest.read_text(encoding="utf-8"))
    return {
        "state": "NOT_VERIFIED",
        "reason": "Hashes are recorded; run scripts/verify_packaged_qemu.py against the actual packaged runtime to verify closure",
        "manifest_path": manifest.relative_to(root).as_posix(),
        "manifest_sha256": sha256_file(manifest),
        "files": [
            {"name": item.get("name"), "bytes": item.get("bytes"), "sha256": item.get("sha256")}
            for item in data.get("files", [])
        ],
    }


def build_manifest(root: Path, lock: dict, entries: list[dict], filelist_bytes: bytes) -> dict:
    return {
        "format": 1,
        "project": "Virtual Android",
        "baseline": "virtual-android-prototype-v0.7",
        "profile": "ci-reproducibility",
        "source_date_epoch": lock["source_date_epoch"],
        "toolchains": lock["toolchains"],
        "source_inventory": {
            "file_count": len(entries),
            "filelist_sha256": sha256_bytes(filelist_bytes),
            "files": entries,
        },
        "runtime_artifacts": {"qemu": qemu_runtime_info(root)},
        "gates": {
            name: {"state": "NOT_VERIFIED", "requirement": requirement}
            for name, requirement in GATES.items()
        },
        "reporting_contract": {
            "verified_value": "VERIFIED",
            "not_verified_value": "NOT_VERIFIED",
            "physical_pass_requires_fresh_same_run_proof": True,
        },
    }


def generate(root: Path) -> tuple[bytes, bytes]:
    lock = load_lock(root)
    entries = inventory(root)
    filelist_bytes = render_filelist(entries)
    manifest = build_manifest(root, lock, entries, filelist_bytes)
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    return filelist_bytes, manifest_bytes


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    ap.add_argument("--check", action="store_true")
    ns = ap.parse_args()
    root = ns.root.resolve()
    filelist_bytes, manifest_bytes = generate(root)
    targets = {
        root / "FILELIST.txt": filelist_bytes,
        root / "release/release-manifest.json": manifest_bytes,
    }
    if ns.check:
        bad = []
        for path, expected in targets.items():
            actual = path.read_bytes() if path.is_file() else b""
            if actual != expected:
                bad.append(path.relative_to(root).as_posix())
        if bad:
            print("Release metadata is stale: " + ", ".join(bad))
            return 2
        print("Release metadata: deterministic and current")
        return 0
    for path, data in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"Wrote {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
